server:
  port: 9000
#spring:
#  kafka:
#    streams:
#      bootstrap-servers: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
#      application-id: my-kafka-streams-application-id
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='????????' password='?????????????????????????????????????????????';
#    consumer:
#      bootstrap-servers: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
#      group-id: metadata-inference-join
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
